version: "3.8"
networks:
    delivery:
        driver: bridge
services:
    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        environment:
            PHP_IDE_CONFIG: serverName=default
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - delivery
        depends_on:
            - php-fpm
    php-fpm:
        build: ./docker/php-fpm
        working_dir: /var/www/
        environment:
            PHP_IDE_CONFIG: serverName=default
        volumes:
            - ./:/var/www
            - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa
        networks:
            - delivery
        depends_on:
            - db
    ### Redis
    redis:
        image: redis:latest
        networks:
            - delivery
        volumes:
            - redis-delivery-data:/data
        ports:
            - 63790:6379
volumes:
    redis-delivery-data:
